### ISSUE TITLE
Ctrl+Esc won't work in any Windows

### ISSUE THREAD

**Issue by laacz** [dryan/decss#2]
Ctrl+Esc in Windows is used to open start menu (synonym for Win key). Presenter mode therefore is not accessible.

**Comment by dryan** [comment]
Fair point. I'll add support for Alt+Esc as well.

**Comment by dryan** [comment]
And that seems to be taken as well. Plain Escape isn't a good choice since that's how one exits fullscreen mode. We'll just go with "p".
